### ISSUE TITLE
New save bug?

### ISSUE THREAD

**Issue by dravpin** [FroggosOrbit/webfishing-true-offline#1]
When starting a new save with true offline you do not start in the tutorial area and instead start at the tree with items calling you stinky lmao not sure if thats an anti modding thing or something? 

edit: tried dm on twitter but you have messages turned off and your discord seems it might be wrong

**Comment by FroggosOrbit** [comment]
Fixed! Sorry for the issue, it was left over from me testing, not anti-modding here's why they happened.

The tutorial was turned off for testing purposes, and i forgot to turn it back on. 

The select items are the dev's starting items, which are just items you normally unlock while playing the game. In my attempt to remove their steam ids from the code, I mistakenly made it to where those items are given to everyone on a new save. This is now fixed

here's the fixed version: https://github.com/FroggosOrbit/webfishing-true-offline/releases/tag/webfishingoffline

**Comment by dravpin** [comment]
Woah cool wasnt expecting a quick response thanks thats kinda cool actually theres quite a bit of dev stuff left over like some grey boxing which i think is really neat anyhow thanks for the fix 👍

**Comment by dravpin** [comment]
one more thing do you mind adding me on discord?
